language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - cd ../
  - mkdir testing
  - cd testing
  - cmake ..
  - make
  - ./tests/brain/brain_test
  - ./tests/eyes/eyes_test
