language: cpp

stages:
  - build
  - test

compiler:
  - gcc

building:
  stage: build
  before_script:
    - mkdir build
    - cd build
    - cmake ..

  script: make

testing:
  stage: test
  script:
    - cd tests
    - ./test.sh
